# Generated by Django 3.2.9 on 2021-12-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['crypto']},
        ),
    ]
