# Generated by Django 3.2.9 on 2021-12-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['symbol']},
        ),
    ]
