# Generated by Django 3.2.9 on 2021-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_updated',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
