# Generated by Django 3.2.9 on 2021-12-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20211203_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
